# Generated by Django 4.2.13 on 2024-05-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_auth',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comm',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='rating',
        ),
    ]
