# Generated by Django 4.2.13 on 2024-07-16 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_rating_auth_author_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribes',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
